### ISSUE TITLE
lowest and highest node layers are protectable

### ISSUE THREAD

**Issue by SwissalpS** [birdlover32767/warzone_modified#1]
wouldn't you want to use ``>=`` and ``<=`` here?

https://github.com/birdlover32767/warzone_modified/blob/fea6ce591aa0ca1ab9b011ffdc796e787d898443/protector.lua#L8

**Comment by birdlover32767** [comment]
this has been fixed

**Comment by birdlover32767** [comment]
oops, accidentally reopened
anyway this has been completed in 63b25b4
